version: "3.8"

services:
  db:
    image: postgres:13
    ports:
      - 54331:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - hw-db-data:/var/lib/postgresql/data
  queue:
    image: library/rabbitmq:3.8-management
    ports:
      - 15673:15672
      - 5673:5672

volumes:
  hw-db-data: